openapi: 3.0.0
info:
  title: 5GMS Common Data Types
  version: 2.0.1
  description: |
    5GMS Common Data Types
    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
tags:
  - name: 5GMS Common Data Types
    description: '5G Media Streaming: Common Data Types'
externalDocs:
  description: 'TS 26.512 V17.4.0; 5G Media Streaming (5GMS); Protocols'
  url: 'https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/'
paths: {}
components:
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
        code:
          type: integer